version: "3"

services:
    gas-api:
        depends_on:
            - gas-db
        build:
            context: ./api
        environment:
            - GAS_DATABASE_SERVER=${GAS_DATABASE_SERVER}
            - GAS_POSTGRES_DB=${GAS_POSTGRES_DB}
            - GAS_POSTGRES_USER=${GAS_POSTGRES_USERNAME}
            - GAS_POSTGRES_PASSWORD=${GAS_POSTGRES_PASSWORD}
            - ASPNETCORE_ENVIRONMENT=${GAS_ENVIRONMENT}
            - GAS_SECRET=${GAS_SECRET}
        ports:
            - "5000:${GAS_PORT}"
        restart: unless-stopped

    gas-db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${GAS_POSTGRES_DB}
            - POSTGRES_USER=${GAS_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${GAS_POSTGRES_PASSWORD}
        volumes:
            - gas-db-data:/var/lib/postgresql/data

volumes:
    gas-db-data:
        driver: local
