version: "3"

services:
    gas-api:
        depends_on:
            -   gas-db
        build:
            context: ./api
        ports:
            - "8081:${GAS_PORT}"
        restart: unless-stopped

    gas-db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${GAS_POSTGRES_DB}
            - POSTGRES_USER=${GAS_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${GAS_POSTGRES_PASSWORD}
        volumes:
            - gas-db-data:/var/lib/postgresql/data

    gas-pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${GAS_DB_ADMIN_MAIL}
            PGADMIN_DEFAULT_PASSWORD: ${GAS_DB_ADMIN_PASSWORD}
        ports:
            - "5050:${GAS_DB_ADMIN_PORT}"
        logging:
            driver: none

volumes:
    gas-db-data:
        driver: local
    pgadmin:
        driver: local
