version: "3"

services:
    gas-api:
        depends_on:
            - gas-db
            - rabbitmq
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        environment:
            - GAS_DATABASE_SERVER=${GAS_DATABASE_SERVER}
            - GAS_POSTGRES_DB=${GAS_POSTGRES_DB}
            - GAS_POSTGRES_USER=${GAS_POSTGRES_USERNAME}
            - GAS_POSTGRES_PASSWORD=${GAS_POSTGRES_PASSWORD}
            - GAS_CDN_URI=${GAS_CDN_URI}
            - GAS_RABBITMQ_HOSTNAME=${GAS_RABBITMQ_HOSTNAME}
            - GAS_MAIL_HOST=${GAS_MAIL_HOST}
            - GAS_MAIL_PORT=${GAS_MAIL_PORT}
            - GAS_MAIL_USERNAME=${GAS_MAIL_USERNAME}
            - GAS_MAIL_PASSWORD=${GAS_MAIL_PASSWORD}
            - GAS_MAIL_SSL=${GAS_MAIL_SSL}
            - GAS_MAIL_ADR_NO_REPLY=${GAS_MAIL_ADR_NO_REPLY}
            - GAS_MAIL_CALLBACK_URL=${GAS_MAIL_CALLBACK_URL}
            - ASPNETCORE_ENVIRONMENT=${GAS_ENVIRONMENT}
            - GAS_SECRET=${GAS_SECRET}
        ports:
            - "5000:${GAS_PORT}"
        volumes:
            - gas-assets-data:/assets
            - ./api:/app
        restart: unless-stopped

    gas-db:
        image: postgres:13.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${GAS_POSTGRES_DB}
            - POSTGRES_USER=${GAS_POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${GAS_POSTGRES_PASSWORD}
        volumes:
            - gas-db-data:/var/lib/postgresql/data

    gas-pgadmin:
        image: dpage/pgadmin4:5
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${GAS_DB_ADMIN_MAIL}
            PGADMIN_DEFAULT_PASSWORD: ${GAS_DB_ADMIN_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "81:${GAS_DB_ADMIN_PORT}"
        logging:
            driver: none
        volumes:
            - gas-pgadmin-data:/var/lib/pgadmin

    gas-nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - gas-assets-data:/usr/share/nginx/wwwroot/assets
            - ./nginx.conf:/etc/nginx/nginx.conf
              
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"


    adminer:
        image: adminer
        ports:
            - "8080:8080"

volumes:
    gas-db-data:
        driver: local
    gas-pgadmin-data:
        driver: local
    gas-assets-data:
        driver: local
