version: 2.1

jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: echo "$DOCKER_PASS" | docker login $REGISTRY_URL --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t $REGISTRY_URL/gas-api:dev ./api/

     # deploy the image
     - run: docker push $REGISTRY_URL/gas-api:dev
      
workflows:
  build-and-deploy: 
    jobs:
      - build:
          context: backend
          # filters:
          #   branches:
          #     only:
          #       - dev
          #       - master
