version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  push-to-registry-latest:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login $REGISTRY_URL --username $DOCKER_USER --password-stdin
      - run: docker build -t $REGISTRY_URL/gas-api:latest ./api/
      - run: docker push $REGISTRY_URL/gas-api:latest
  push-to-registry-production:
    machine: true
    steps:
     - checkout
     - run: echo "$DOCKER_PASS" | docker login $REGISTRY_URL --username $DOCKER_USER --password-stdin
     - run: docker build -t $REGISTRY_URL/gas-api:production ./api/
     - run: docker push $REGISTRY_URL/gas-api:production
  rollout-latest:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      # - kubernetes/update-container-image:
      #     container-image-updates: 'gas-api=registry.gameadsstudio.com/gas-api:latest'
      #     get-rollout-status: true
      #     record: true
      #     resource-name: deployment/gas-api-deployment
      #     watch-timeout: '5m'
      - run: kubectl rollout restart deploy/gas-api-deployment
      - kubernetes/get-rollout-status:
          resource-name: deployment/gas-api-deployment
      
workflows:
  build-and-deploy: 
    jobs:
      - push-to-registry-latest:
          context: registry
          filters:
            branches:
              only:
                - dev
      - push-to-registry-production:
          context: registry
          filters:
            branches:
              only:
                - master
      - rollout-latest:
          requires:
            - push-to-registry-latest
